global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'bakerbot-monitor'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8099' ] # Измените на новый порт 9091